name: Release Automática

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true # Força o uso do Node.js 24 conforme o aviso
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4.1.7 # Versão atualizada

      - name: Configurar Java
        uses: actions/setup-java@v4.2.1 # Versão atualizada
        with:
          java-version: '17' # Mantendo a versão que resolve conflitos de classe
          distribution: 'temurin'
          cache: 'maven'

      - name: Build com Maven
        run: mvn clean package

      - name: Criar Release e Upload do Plugin
        uses: softprops/action-gh-release@v2 # Atualizado para v2 que suporta Node 24
        with:
          files: target/*.jar
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}